### ISSUE TITLE
Authentication - Create a way to keep the user logged in

### ISSUE THREAD

**Issue by gleybersonandrade** [kytos/kytos#1008] opened 2019-12-17 15:09 UTC
Today, the authentication module has no way to renew the user token; If it expires, the user must authenticate again. We have to create a session or something to keep the user logged in.

**Comment by gleybersonandrade** [comment] 2020-08-19 12:42
Related #1128

**Comment by hdiogenes** [comment] 2020-10-22 18:40
Duplicate of #1013

**Closed as completed by hdiogenes** 2020-10-22 18:40 UTC
Labels: enhancement
