### ISSUE TITLE
catch AttributeErrors instead of checking for attribute

### ISSUE THREAD

**Issue by erickvermot** [kytos/kytos#480] opened 2017-06-26 14:32 UTC
Checking for an attribute that may not exist anymore before using it is not enough when concurrent methods may affect it. We need to try to use and catch the AttributeError exceptions in all these cases.

https://github.com/kytos/kytos/issues/466 is an example of this behavior, there are other in the code.
I'm opening this issue so we can identify them and fix each one.

**Comment by cemsbr** [comment] 2017-08-03 17:34
As we don't have any reproducible example since 466 was closed, I'm closing this issue.

**Closed as completed by cemsbr** 2017-08-03 17:34 UTC
