### ISSUE TITLE
Pin the requirements versions for `2017.1`

### ISSUE THREAD

**Issue by macartur** [kytos/kytos#537] opened 2017-07-18 16:48 UTC
In order to avoid future problems with packages updates that breaks compatibility or that introduce unexpected errors/behaviors, we must pin all of our requirements versions for each release. Including the requirements of the requirements.

So, for our 2017.1 release we must pin the requirements.

**Comment by cemsbr** [comment] 2017-07-18 21:48
Closing as duplicate of #464.

**Closed as completed by cemsbr** 2017-07-18 21:48 UTC
Labels: level:easy, pri:important
