### ISSUE TITLE
setup.py not installing all dependencies

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos#357] opened 2017-04-19 12:12 UTC
Started a new environment and ran `python setup.py install` for python-openflow, kytos-utils and kytos, and no errors ocurred. However, when I ran `kytosd -f`, all I've got was:
```
Traceback (most recent call last):
  File "/home/renan/testes/venv/bin/kytosd", line 3, in <module>
    import daemon
ModuleNotFoundError: No module named 'daemon'
```

**Comment by diraol** [comment] 2017-04-24 13:11
May be we could use this setuptools function to achieve our needs:
https://github.com/pypa/setuptools/blob/e65c45538fab94008b8066edd134725be8f9c400/bootstrap.py#L75

**Comment by abaruchi** [comment] 2017-04-24 14:38
@renanrodrigo I run some tests to reproduce the error. I think that the procedure in kytos tutorial may be wrong. Can you please try the following:
```
for project in python-openflow kytos-utils kytos-napps kytos; do 
cd $project 
pip3.6 install -r requirements.txt -r requirements-dev.txt -r requirements-docs.txt >/tmp/requirements.$project.log 2>&1 
python3.6 setup.py develop >/tmp/setup.$project.log 2>&1 
cd - 
done
```
Note that `s/pip/pip3.6/` and `s/python/python3.6/` inside the for looping.

**Comment by renanrodrigo** [comment] 2017-04-24 17:41
@abaruchi I know it works that way, I'm doing this for a while. But `pythons setup.py install` should install all dependencies. @macartur posted a bug in setuptools that may be causing this.

**Comment by macartur** [comment] 2017-04-24 17:43
This is the issue: pypa/setuptools#456.

**Comment by diraol** [comment] 2017-04-24 17:45
@renanrodrigo and @macartur dos this issue affects both `install` mode and `develop` mode? or just `install`?
[I'm working on a solution for us]

**Comment by diraol** [comment] 2017-04-24 17:50
Btw, this comment seems to be the real issue for us:
https://github.com/pypa/setuptools/issues/456#issuecomment-202922033

**Comment by renanrodrigo** [comment] 2017-04-24 19:19
@diraol develop mode works fine.

**Comment by diraol** [comment] 2017-04-24 19:23
Ok, then the problem is the one from this comment:
https://github.com/pypa/setuptools/issues/456#issuecomment-202922033

If on our `Install` class (inside `setup.py`) we call the `self.do_egg_install()` instead of `super().run()`, then almost everything works fine.
I mean, the main problem (of installing dependencies) is solved.

The only remaining problem is that, despite the fact that `jinja2` is installed by the `setup` script, it is not available to the `setup` script itself [the modules available on the Path are not "reloaded"], so we still have to deal with the `Jinja2` import error.

**Comment by cemsbr** [comment] 2017-04-26 17:10
#375 also solves this problem.

**Comment by diraol** [comment] 2017-04-26 17:17
@cemsbr please, reference the issue on the commit! =)

**Comment by beraldoleal** [comment] 2017-05-02 15:53
@diraol @cemsbr #375 was merged but without reference to here, right ? Can we close this ?

**Comment by diraol** [comment] 2017-05-02 16:47
Yes we can @beraldoleal !

**Closed as completed by diraol** 2017-05-02 16:47 UTC
Labels: pri:blocker, pri:critical
