### ISSUE TITLE
Authentication - Create a configuration field to change token expiration time

### ISSUE THREAD

**Issue by gleybersonandrade** [kytos/kytos#1009] opened 2019-12-17 15:13 UTC
Token expiration time is hardcoded. We have to create a field in the configuration file to give the user the ability to choose their value.

**Comment by gleybersonandrade** [comment] 2020-08-19 12:42
Related #1128

**Comment by hdiogenes** [comment] 2020-10-22 18:39
Duplicate of #1007

**Closed as completed by hdiogenes** 2020-10-22 18:39 UTC
Labels: enhancement
